### ISSUE TITLE
Generating the schema should be deterministic

### ISSUE THREAD

**Issue by eriksvedang** [coherence/protocol-code-generator#134]
While it *is* useful to see the date when the current output of the protocol-code-generator was created, it also messes unnecessarily with both Git and Unity (triggering unnecessary reloads of the scripts). 

My suggestion is to make the generated output 100% deterministic to solve this problem (= remove the date).

We could stamp the schema with what version of the protocol-code-generator that was used to produce it though, since that is useful for debugging.

**Comment by kingstone426** [comment]
I agree completely. This way we can also compare schema hashes to ensure e.g. client and server actually run the same schema.
