### ISSUE TITLE
Wrong Method name generated for FixedString64

### ISSUE THREAD

**Issue by tadej** [coherence/protocol-code-generator#145]
Schema:
component PlayerName
  name String64

`public static void PlayerName(IInBitStream bitstream, ref PlayerName data)
{
var name = bitstream.ReadShortString();
data.name = CoherenceToUnityConverters.ToUnityFixedString64(name);
}`

ToUnityFixedString64 does not exist anymore (change to ToUnityNativeString64).

Assets\coherence\generated\schema.cs(3416,44): error CS0117: 'CoherenceToUnityConverters' does not contain a definition for 'ToUnityFixedString64'

**Comment by tadej** [comment]
We do have `ToUnityNativeString64`, which works.

**Comment by tadej** [comment]
(apparently ToUnityFixedString64 was removed in latest Entities, this is why we need unit tests)

**Comment by eriksvedang** [comment]
Seems like the name change was in one of our own libraries (replication-client-unity). Not sure why it was made actually...

**Comment by eriksvedang** [comment]
A follow up question is where the unit tests that presumably would catch this should be located? They must run the protocol-code-generator *and* compile the emitted code with Unity, right? (nightly builds for the projects seems like it will serve at least some of the same purpose, even though unit tests would be great too of course)

**Comment by tadej** [comment]
@eriksvedang I agree, the nightly builds (assuming that they compile the protocol code) would catch this as well.

The tests could make sure that all the types and conversions from Unity's packages actually still exist. Perhaps the proper name is more Integration tests?

/cc @ottov1

**Comment by ottov1** [comment]
The nightly builds don't compile the protocol code but it's not that hard to add it. I'll se if I can squeeze it in.

@tadej I like Integration Tests more than nightly builds - it's more correct too, given that we don't actually output any builds :)
