### ISSUE TITLE
Update protocol-code-generator to apply replication-client refactoring.

### ISSUE THREAD

**Issue by kingstone426** [coherence/protocol-code-generator#155]

**Comment by eriksvedang** [comment]
I'm a bit mystified by the title of this issue :D
I should bump the dependency to latest and fix the compiler errors..?

**Comment by eriksvedang** [comment]
see https://github.com/coherence/sdk-testbed-spacewars/tree/replication-refactor-test

**Comment by eriksvedang** [comment]
and https://github.com/coherence/replication-client-unity/tree/extract-send-systems
