### ISSUE TITLE
The --help flag should contain information about help for subcommands

### ISSUE THREAD

**Issue by eriksvedang** [coherence/protocol-code-generator#99]
Right now `$ coherence-protocol-code-generator --help ` emits:

```bash
Usage: coherence-protocol-code-generator <command>

Flags:
  --help                          Show context-sensitive help.
  --log-level=LOG-LEVEL-STRING    the log level
  --log-file=LOG-FILE-STRING      log output file

...
```

The cli interface would be more discoverable it there was an additional line of 

```bash
  --help <command>         Show context-sensitive help for a subcommand.
```

**Comment by piot** [comment]
Good suggestion!

**Comment by eriksvedang** [comment]
Looking into this I see that the structure of the help output is controlled by the [Kong](https://github.com/alecthomas/kong) library, so fixing this would probably need upstream patching actually. Might not be worth it?

**Comment by eriksvedang** [comment]
I'll close this issue for now, I don't think my suggestion makes that much sense (after thinking about it some more).
